### PR TITLE
Changes for windows users integration path in GIMP

### PR DESCRIPTION
**Pull request by AlexDeveloper714**
This change help windows users to install Gimp2Synfig plugin inside Windows :)

### CODE REVIEW

**Comment by d-j-a-y** [comment]
Could do you think to fix your contribution by adding a link to gimp official documentation about plugins install ? (for each platforms could be awesome :-)

**Comment by AlexDeveloper714** [comment]
I could try :D, but not now, sorry about that :/
I would do that when I´m in holiday season :D

**Comment by AlexDeveloper714** [comment]
Please try this in other OS installations, I only have windows (because I need it a lot :( )
and tell me if this commit can help all users :D

**Comment by d-j-a-y** [comment]
thank's for your contribution AlexDev"

**Pull request merged**
